### ISSUE TITLE
Exit with error code

### ISSUE THREAD

**Issue by sigveka** [OpenFOAM/OpenFOAM-5.x#1]
Greetings FOAMers,

I am attempting to exit FOAM with a specific exit code (integer) e.g.:

```
Foam::error e("My error");
e.exit(100);
```

But the error code that results is `1`.

Looking at line 203 of `error.C` this is obvious because the error code is hard-coded to be `1`.
However, from my superficial vantage point I do not see an obvious reason why you are using `1` instead of `errNo` when considering that the default value of `errNo` is `1` (from the header file).

Am I ab/mis-using your error handling system by doing this?

Regards,

Sigve

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php
