### ISSUE TITLE
Bug about surfaceTension implement in reactingmultiphaseEulerFoam ？

### ISSUE THREAD

**Issue by graceyangfan** [OpenFOAM/OpenFOAM-5.x#2]
Hello.I am studying the reactingmultiphaseEulerFoam,
the code for surfaceTension implement is:
https://github.com/OpenFOAM/OpenFOAM-5.x/blob/7f7d351b741bf6406366a043cac98de56d2d44dd/applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/pU/pEqn.H#L137
 

forAll(phases, phasei)
    {
        phaseModel& phase = phases[phasei];

        phigs.set
        (
            phasei,
            (
                alpharAUfs[phasei]
               *(
                   ghSnGradRho
                 - (fvc::interpolate(phase.rho() - rho))*(g & mesh.Sf())
                 - fluid.surfaceTension(phase)*mesh.magSf()
                )
            ).ptr()
        );
    }

finnaly,the velocity is updated by:

               phase.U() =
                    HbyAs[phasei]
                  + fvc::reconstruct
                    (
                        alpharAUfs[phasei]*mSfGradp
                      - phiFs[phasei]
                      - phigs[phasei]
                    );

It seems that the code updated velocity as:
![image](https://user-images.githubusercontent.com/17508779/61933300-29b3c000-afb8-11e9-9f0c-f60759476f3c.png)
My derivation mathematical formula is:
![image](https://user-images.githubusercontent.com/17508779/61933381-536ce700-afb8-11e9-9255-1931029aca27.png)
please check the code

**Comment by OpenFOAM** [comment]
https://bugs.openfoam.org/rules.php
